inherit_gem:
  rubocop-vinted:
    - .rubocop.default.yml

AllCops:
  TargetRubyVersion: 3.2.2
  DisplayCopNames: true
  Exclude:
    - db/**/*

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/factories/**/*.rb'